# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20160408_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
